version: 2

jobs:
  sbcl:
    docker:
      - image: cimg/base:2022.09
    environment:
      LISP: sbcl-bin
    steps:
      - checkout
      # This is the only way CircleCI allows setting environmental variables accross steps
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$HOME/.roswell/bin:$PATH" >> $BASH_ENV

      - run: echo $LISP
      - run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
      #- run: ros install neil-lindquist/ci-utils # for run-fiveam
      - run: ros install prove # for run-prove
      - run: ros install gadgets # SBCL/quicklisp/CircleCI don't load right. This should help.
      #- run: ros install rove # for [run-] rove

      #- run: run-fiveam -e t -l foo/test :foo-tests
      - run: run-prove test-gadgets.asd
      #- run: rove foo.asd
  ccl:
    docker:
      - image: circleci/buildpack-deps:stretch-curl
    environment:
      LISP: ccl-bin
    steps:
      - checkout
      # This is the only way CircleCI allows setting environmental variables accross steps
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$HOME/.roswell/bin:$PATH" >> $BASH_ENV

      - run: echo $LISP
      - run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
      #- run: ros install neil-lindquist/ci-utils # for run-fiveam
      - run: ros install prove # for run-prove
      #- run: ros install rove # for [run-] rove

      #- run: run-fiveam -e t -l foo/test :foo-tests
      - run: run-prove test-gadgets.asd
      #- run: rove foo.asd



workflows:
  version: 2
  run_tests:
    jobs:
      - sbcl
      - ccl
  
